name: CI/CD Pipeline for Flask App on Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # ✅ Correct version

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2  # ✅ Correct version
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # ✅ Secure authentication

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2  # ✅ Correct version

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev  # ✅ Matches the region

      - name: Build & Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-flask-app-repo/my-flask-app:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-flask-app-repo/my-flask-app:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-flask-app-repo/my-flask-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
